#!/bin/bash

base=$(dirname $0)

if [ -z "$1" ] ; then
  echo "(Did you mean 'gits help' maybe?)"
  $base/commands/status
elif [ "$1" == "--help" ] ; then
  $base/commands/help
  exit 255
elif [ -e "$base/commands/$1" ] ; then
  command="$base/commands/$1"
  shift
  $command $*
else
  echo "Invalid command: $1"
  exit 1
fi

