#!/bin/bash

base=$(dirname $0)
script_path=$base/gits

if [ "$1" == "--help" ] ; then
  echo "show this help"
  exit 1
elif [ "$1" == "--inline" ] ; then
  for x in `ls -1 $base/gits*` ; do
    command=${x##$base/gits-}
    if [ -n $command -a $command != $script_path ] ; then
      echo -n "$command "
    fi
  done
  exit 2
fi

echo "Usage: gits COMMAND [ARGUMENTS...]"
echo
echo "Commands:"
for x in `ls -1 $base/gits*` ; do
  command=${x##$base/gits-}
  if [ -n $command -a $command != $script_path ] ; then
    description=$($script_path-$command --help)
    echo "    $command: $description"
  fi
done

