#!/bin/bash

source "$(dirname $0)/../colors"
source "$(dirname $0)/../logger"

if [ "$1" == "--description" ] ; then
  echo "show the changes between versions"
  exit 1
elif [ "$1" == "--help" ] ; then
  echo "Usage: gits $(basename $0) [--help] [--all] [--csv] [--since DATE] [--until DATE] FROM [TO]"
  echo
  echo "Options:"
  echo "    --help             show this message"
  echo "    --all              look at all refs"
  echo "    --csv              print changes as CSV records"
  echo "    --since=<date>     show changes newer than this date"
  echo "    --until=<date>     show changes older than this date"
  echo "    --ignore=<regepx>  ignore commit messages matching the regexp"
  echo
  echo "Arguments:"
  echo "    FROM the starting tag"
  echo "    TO   the end tag (or HEAD if none)"
  exit 1
fi

if echo $OSTYPE | grep -qiE "(solaris|darwin)" ; then
  args=$(getopt "$short" $@ 2>&1)
  if [ $? != 0 ] ; then
    error $args
    exit 1
  fi
else
  args=`getopt -o "h,a,c,s:,u:,i:" -l "help,all,csv,since:,until:,ignore:" -- "$@"` || fatal "Invalid arguments"
fi

eval set -- "$args"
while [ $# != 0 ] ; do
  opt="$1"; shift;
  case "$opt" in
    -c|--csv)
      csv=1;;
    -a|--all)
      all=1;;
    -s|--since)
      since=$1 && shift;;
    -u|--until)
      until=$1 && shift;;
    -i|--ignore)
      ignore=$1 && shift;;
    --)
      break;;
  esac
done

tag="$1"
dest="${2-HEAD}"

if [[ "$tag" == "" && "$since" == "" && "$until" == "" ]] ; then
  fatal "Missing tag"
fi

TMP_FILE=/tmp/changelog.$$
echo -n > $TMP_FILE

root="$PWD"
for x in `find . -type d -name ".git" | grep -v checkout | sort` ; do
  cd $root/$x/..

  repo=$(basename $PWD)

  command="git log --no-merges"

  if [ -n "$csv" ] ; then
    command="$command --format=format:$repo;%ai;%an;%s"
  else
    command="$command --format=(%ad)%x20[%an]%x20%s"
  fi

  if [ -n "$all" ] ; then
    command="$command --all"
  fi
  if [ -n "$since" ] ; then
    command="$command --since $since"
  fi
  if [ -n "$until" ] ; then
    command="$command --until $until"
  fi

  if [ -n "$tag" ] ; then
    tags=`git tag | grep "$tag" | wc -l | sed -e "s/ //g"`
    if [[ $tags == 0 ]] ; then
      if [ -z "$csv" ] ; then
        info "*** $repo ***"      
        warn "Can't find match for '$tag'"
        echo
      fi
      continue
    elif [[ $tags > 1 ]] ; then
      if [ -z "$csv" ] ; then
        info "*** $repo ***"      
        warn "Found multiple matches for '$tag':"
        git tag | grep "$tag"
        echo
      fi
      continue
    fi
    repo_tag=`git tag | grep "$tag"`
    command="$command $repo_tag..$dest"
  fi

  if [ -n "$ignore" ] ; then
    $command -- | grep -vE "$ignore" > $TMP_FILE
  else
    $command -- > $TMP_FILE
  fi

  if [ -n "$csv" ] ; then
    cat $TMP_FILE
  else
    info "*** $repo ***"
    if [ -s "$TMP_FILE" ] ; then
      cat $TMP_FILE
    else
      debug "No changes"
    fi
    echo
  fi

done

