#!/bin/bash

base=$(dirname $0)
script_path=$base/gits

source "$base/../colors"

if [ "$1" == "--description" ] ; then
  echo "show this help"
  exit 1
elif [ "$1" == "--help" ] ; then
  echo "Usage: gits $(basename $0) [--help] [COMMAND]"
  echo
  echo "Options:"
  echo "    --help show this message"
  echo
  echo "Arguments:"
  echo "    COMMAND show the usage of the command"
  exit 1
elif [ "$1" == "--inline" ] ; then
  for x in `ls -1 $base/*` ; do
    echo -n "$(basename $x) "
  done
  exit 2
elif [ -n "$1" ] ; then
  if [ -e "$base/$1" ] ; then
    $base/$1 --help
  else
    echo -e "${C_RED}Unknown command: $1${C_OFF}"
  fi
else
  echo "Usage: gits COMMAND [ARGUMENTS...]"
  echo
  echo "Commands:"
  for x in `ls -1 $base/*` ; do
    name=$(basename $x)
    description=$($x --description)
    echo "    $name: $description"
  done
fi

