#!/bin/bash

source "$(dirname $0)/../colors"

if [ "$1" == "--help" ] ; then
  echo "show the status of all the git repositories"
  exit 1
fi

root="$PWD"
for x in `find . -type d -name ".git" | grep -v checkout | sort` ; do
  cd $root/$x/..

  branch=$(git branch | grep '*' | cut -c3-)

  if [[ $(git status 2> /dev/null | tail -n1) == "nothing to commit, working directory clean" ]] ; then
    echo -e "$(basename $PWD): ${C_GREEN}$branch${C_OFF}"
  else
    echo -e "$(basename $PWD): ${C_YELLOW}$branch${C_OFF} (local changes)"
  fi
done

