#!/bin/bash

source "$(dirname $0)/../colors"

if [ "$1" == "--description" ] ; then
  echo "show the status of all the git repositories"
  exit 1
elif [ "$1" == "--help" ] ; then
  echo "Usage: gits $(basename $0) [--help] [--full]"
  echo
  echo "Options:"
  echo "    --help show this message"
  echo "    --full show the modified files"
  exit 1
fi

root="$PWD"
for x in `find . -type d -name ".git" | grep -v checkout | sort` ; do
  cd $root/$x/..

  branch=$(git branch | grep '*' | cut -c3-)

  last_line=$(git status 2> /dev/null | tail -n1)
  if [[ $last_line == "nothing to commit, working directory clean" ]] ; then
    echo -e "$(basename $PWD): ${C_GREEN}$branch${C_OFF}"
  elif [[ $last_line =~ nothing\ added\ to\ commit\ but\ untracked\ files\ present.* ]] ; then
    echo -e "$(basename $PWD): ${C_YELLOW}$branch${C_OFF} (untracked files)"
  else
    echo -e "$(basename $PWD): ${C_RED}$branch${C_OFF} (local changes)"
    if [ "$1" == "--full" ] ; then
      git status --short
    fi
  fi
done

