#!/bin/bash

source "$(dirname $0)/../colors"
source "$(dirname $0)/../logger"

if [ "$1" == "--description" ] ; then
  echo "switch all git repositories to a branch"
  exit 1
elif [ "$1" == "--help" ] ; then
  echo "Usage: gits $(basename $0) [--help] BRANCH"
  echo
  echo "Options:"
  echo "    --help show this message"
  echo
  echo "Arguments:"
  echo "    BRANCH the branch to switch to"
  exit 1
fi

branch="$1"

if [ -z "$branch" ] ; then
  fatal "Missing branch"
fi

root="$PWD"
for x in `find . -type d -name ".git" | grep -v checkout` ; do
  cd $root/$x/..
 
  echo -n "$(basename $PWD): "
  if $(git branch | grep "* $branch" > /dev/null ) ; then
    echo -e "${C_GREEN}already on $branch${C_OFF}"
    git pull
  elif $(git branch | grep " $branch" > /dev/null) ; then
    echo -e "${C_YELLOW}updating $branch${C_OFF}"
    git checkout $branch && git pull
  else
    echo -e "${C_YELLOW}checking out $branch${C_OFF}"
    git fetch && git checkout $branch
  fi
done

